const MMConstants = {
    platformIos: 'ios',
    platformAndroid: 'android',
    emailRegex: '[a-z0-9]+@[a-z]+.[a-z]{2,3}',
    toastDuration: 3000,

    dateTimePickerTime: 'hh:mm A',

    otpTimeOut: 60000,

    chapters: {
        pregnancy: require('../assets/images/chapter/pregnancy.png'),
        adoption: require('../assets/images/chapter/adoption.png'),
        surrogacy: require('../assets/images/chapter/surrogacy.png'),
        parents: require('../assets/images/chapter/parents.png'),
        family: require('../assets/images/chapter/family.png'),
        welcomeToTheWorld: require('../assets/images/chapter/welcomeToTheWorld.png'),
        newborn: require('../assets/images/chapter/newborn.png'),
        oneMonth: require('../assets/images/chapter/oneMonth.png'),
        twoMonths: require('../assets/images/chapter/twoMonths.png'),
        threeMonths: require('../assets/images/chapter/threeMonths.png'),
        fourMonths: require('../assets/images/chapter/fourMonths.png'),
        fiveMonths: require('../assets/images/chapter/fiveMonths.png'),
        sixMonths: require('../assets/images/chapter/sixMonths.png'),
        sevenMonths: require('../assets/images/chapter/sevenMonths.png'),
        eightMonths: require('../assets/images/chapter/eightMonths.png'),
        nineMonths: require('../assets/images/chapter/nineMonths.png'),
        tenMonths: require('../assets/images/chapter/tenMonths.png'),
        elevenMonths: require('../assets/images/chapter/elevenMonths.png'),
        oneYear: require('../assets/images/chapter/oneYear.png'),
    },
    milestones: {
        smile: require('../assets/images/milestone/smile.png'),
        laugh: require('../assets/images/milestone/laugh.png'),
        timeRolledOver: require('../assets/images/milestone/timeRolledOver.png'),
        timeBabbled: require('../assets/images/milestone/timeBabbled.png'),
        timeSittingUp: require('../assets/images/milestone/timeSittingUp.png'),
        timeCrawling: require('../assets/images/milestone/timeCrawling.png'),
        tooth: require('../assets/images/milestone/tooth.png'),
        timePullingUpToStand: require('../assets/images/milestone/timePullingUpToStand.png'),
        steps: require('../assets/images/milestone/steps.png'),
        word: require('../assets/images/milestone/word.png'),
        solidMeal: require('../assets/images/milestone/solidMeal.png'),
        nightInOwnRoom: require('../assets/images/milestone/nightInOwnRoom.png'),
        sleptThroughTheNight: require('../assets/images/milestone/sleptThroughTheNight.png'),
        socialOuting: require('../assets/images/milestone/socialOuting.png'),
        familyHoliday: require('../assets/images/milestone/familyHoliday.png'),
        christmas: require('../assets/images/milestone/christmas.png'),
        easter: require('../assets/images/milestone/easter.png'),
        wavedHelloGoodbye: require('../assets/images/milestone/wavedHelloGoodbye.png'),
        mothersDay: require('../assets/images/milestone/mothersDay.png'),
        fathersDay: require('../assets/images/milestone/fathersDay.png'),
        ultraSound: require('../assets/images/milestone/ultraSound.png'),
        babyMoveKick: require('../assets/images/milestone/babyMoveKick.png'),
        bath: require('../assets/images/milestone/bath.png'),
        swimming: require('../assets/images/milestone/swim.png'),
        birthday: require('../assets/images/milestone/birthday.png'),
        beachday: require('../assets/images/milestone/beachHoliday.png'),
    },
    templates: {
        "Blank": require('../assets/images/template/Blank.png'),
        "Column2": require('../assets/images/template/Column2.png'),
        "Row2": require('../assets/images/template/Row2.png'),
        "Row2-Column2": require('../assets/images/template/Row2-Column2.png'),
        "Column2-Row": require('../assets/images/template/Column2-Row.png'),
        "Row-Column2": require('../assets/images/template/Row-Column2.png'),
        "Column-Row2": require('../assets/images/template/Column-Row2.png'),
        "Row2-Column": require('../assets/images/template/Row2-Column.png'),
        "Column1-Row3": require('../assets/images/template/Column1-Row3.png'),
        "Row3-Column1": require('../assets/images/template/Row3-Column1.png'),
        "Row1-Column3": require('../assets/images/template/Row1-Column3.png'),
        "Column3-Row1": require('../assets/images/template/Column3-Row1.png'),
        "Row3-Column3": require('../assets/images/template/Row3-Column3.png'),
        "Row4-Column4": require('../assets/images/template/Row4-Column4.png'),
    },

    paddingMedium: 5,
    paddingLarge: 10,
    marginSmall: 5,
    marginMedium: 10,
    marginLarge: 20,
};

export default MMConstants;
